USE MASTER;
GO;

IF DB_ID('UNIVERSITY') IS NOT NULL
    DROP DATABASE UNIVERSITY;
GO

CREATE DATABASE UNIVERSITY;
GO;

USE UNIVERSITY;
GO;

CREATE TABLE POSITION (
    POSITION_NAME NVARCHAR(50) PRIMARY KEY
);

CREATE TABLE FACULTY (
    FACULTY NVARCHAR(10) PRIMARY KEY,
    FACULTY_NAME NVARCHAR(100)
);

CREATE TABLE PULPIT (
    PULPIT NVARCHAR(10) PRIMARY KEY,
    FACULTY NVARCHAR(10),
    PULPIT_NAME NVARCHAR(150),
    CONSTRAINT FK_PULPIT_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
);

CREATE TABLE DISCIPLINE (
    DISCIPLINE NVARCHAR(10) PRIMARY KEY,
    PULPIT NVARCHAR(10),
    DISCIPLINE_NAME NVARCHAR(150),
    CONSTRAINT FK_DISCIPLINE_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    POSITION_NAME NVARCHAR(50),
    PULPIT NVARCHAR(10),
    NAME NVARCHAR(150),
    PHONE NCHAR(12),
    CONSTRAINT FK_EMPLOYEE_POSITION
        FOREIGN KEY (POSITION_NAME)
        REFERENCES POSITION(POSITION_NAME),
    CONSTRAINT FK_EMPLOYEE_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
);

CREATE TABLE PULPIT_MANAGER (
    MANAGER_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    PULPIT NVARCHAR(10),
    CONSTRAINT FK_PULPIT_MANAGER_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_PULPIT_MANAGER_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
);

CREATE TABLE FACULTY_MANAGER (
    MANAGER_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    FACULTY NVARCHAR(10),
    CONSTRAINT FK_FACULTY_MANAGER_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_FACULTY_MANAGER_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
);

CREATE TABLE SPECIALITY (
    SPECIALITY_CODE NVARCHAR(10) PRIMARY KEY,
    FACULTY NVARCHAR(10),
    SPECIALITY_NAME NVARCHAR(100),
    QUALIFICATION NVARCHAR(100),
    CONSTRAINT FK_SPECIALITY_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
);

CREATE TABLE "GROUP" (
    GROUP_ID INT PRIMARY KEY,
    SPECIALITY_CODE NVARCHAR(10),
    START_YEAR INT,
    CONSTRAINT FK_GROUP_SPECIALITY
        FOREIGN KEY (SPECIALITY_CODE)
        REFERENCES SPECIALITY(SPECIALITY_CODE)
);

CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY,
    GROUP_ID INT,
    NAME NVARCHAR(100),
    BIRTH_DATE DATE,
    PHONE NCHAR(12),
    CONSTRAINT FK_STUDENT_GROUP
        FOREIGN KEY (GROUP_ID)
        REFERENCES "GROUP"(GROUP_ID)
);

CREATE TABLE ADDRESS (
    ADDRESS_ID INT PRIMARY KEY,
    REGION NVARCHAR(15),
    CITY NVARCHAR(20),
    STREET NVARCHAR(25),
    BUILDING_NUMBER NVARCHAR(5)
);

CREATE TABLE BUILDING (
    BUILDING_ID NVARCHAR(5) PRIMARY KEY,
    BUILDING_ADDRESS INT,
    CONSTRAINT FK_BUILDING_ADDRESS
        FOREIGN KEY (BUILDING_ADDRESS)
        REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE NVARCHAR(10) PRIMARY KEY,
    AUDITORIUM_NAME NVARCHAR(30)
);

CREATE TABLE AUDITORIUM (
    AUDITORIUM NVARCHAR(10) PRIMARY KEY,
    AUDITORIUM_TYPE NVARCHAR(10),
    BUILDING_ID NVARCHAR(5),
    CAPACITY INT,
    CONSTRAINT FK_AUDITORIUM_BUILDING
        FOREIGN KEY (BUILDING_ID)
        REFERENCES BUILDING(BUILDING_ID)
);