CREATE TABLESPACE TS_UNIVERSITY
    DATAFILE 'tbs_university'
    SIZE 5M
    AUTOEXTEND ON NEXT 1M
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K;

CREATE TABLE POSITION (
    POSITION_NAME NVARCHAR2(50) PRIMARY KEY
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE FACULTY (
    FACULTY NVARCHAR2(10) PRIMARY KEY,
    FACULTY_NAME NVARCHAR2(100)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE PULPIT (
    PULPIT NVARCHAR2(10) PRIMARY KEY,
    FACULTY NVARCHAR2(10),
    PULPIT_NAME NVARCHAR2(150),
    CONSTRAINT FK_PULPIT_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE DISCIPLINE (
    DISCIPLINE NVARCHAR2(10) PRIMARY KEY,
    PULPIT NVARCHAR2(10),
    DISCIPLINE_NAME NVARCHAR2(150),
    CONSTRAINT FK_DISCIPLINE_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    POSITION_NAME NVARCHAR2(50),
    PULPIT NVARCHAR2(10),
    NAME NVARCHAR2(150),
    PHONE NCHAR(12),
    CONSTRAINT FK_EMPLOYEE_POSITION
        FOREIGN KEY (POSITION_NAME)
        REFERENCES POSITION(POSITION_NAME),
    CONSTRAINT FK_EMPLOYEE_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE PULPIT_MANAGER (
    MANAGER_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    PULPIT NVARCHAR2(10),
    CONSTRAINT FK_PULPIT_MANAGER_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_PULPIT_MANAGER_PULPIT
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE FACULTY_MANAGER (
    MANAGER_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    FACULTY NVARCHAR2(10),
    CONSTRAINT FK_FACULTY_MANAGER_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_FACULTY_MANAGER_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE SPECIALITY (
    SPECIALITY_CODE NVARCHAR2(10) PRIMARY KEY,
    FACULTY NVARCHAR2(10),
    SPECIALITY_NAME NVARCHAR2(100),
    QUALIFICATION NVARCHAR2(100),
    CONSTRAINT FK_SPECIALITY_FACULTY
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE "GROUP" (
    GROUP_ID INT PRIMARY KEY,
    SPECIALITY_CODE NVARCHAR2(10),
    START_YEAR INT,
    CONSTRAINT FK_GROUP_SPECIALITY
        FOREIGN KEY (SPECIALITY_CODE)
        REFERENCES SPECIALITY(SPECIALITY_CODE)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY,
    GROUP_ID INT,
    NAME NVARCHAR2(100),
    BIRTH_DATE DATE,
    PHONE NCHAR(12),
    CONSTRAINT FK_STUDENT_GROUP
        FOREIGN KEY (GROUP_ID)
        REFERENCES "GROUP"(GROUP_ID)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE ADDRESS (
    ADDRESS_ID INT PRIMARY KEY,
    REGION NVARCHAR2(15),
    CITY NVARCHAR2(20),
    STREET NVARCHAR2(25),
    BUILDING_NUMBER NVARCHAR2(5)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE BUILDING (
    BUILDING_ID NVARCHAR2(5) PRIMARY KEY,
    BUILDING_ADDRESS INT,
    CONSTRAINT FK_BUILDING_ADDRESS
        FOREIGN KEY (BUILDING_ADDRESS)
        REFERENCES ADDRESS(ADDRESS_ID)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE NVARCHAR2(10) PRIMARY KEY,
    AUDITORIUM_NAME NVARCHAR2(30)
)
TABLESPACE TS_UNIVERSITY;

CREATE TABLE AUDITORIUM (
    AUDITORIUM NVARCHAR2(10) PRIMARY KEY,
    AUDITORIUM_TYPE NVARCHAR2(10),
    BUILDING_ID NVARCHAR2(5),
    CAPACITY INT,
    CONSTRAINT FK_AUDITORIUM_BUILDING
        FOREIGN KEY (BUILDING_ID)
        REFERENCES BUILDING(BUILDING_ID)
)
TABLESPACE TS_UNIVERSITY;
